{
  'tabWidth': 2,
  'semi': false,
  'singleQuote': true,
  'bracketSpacing': true,
  'arrowParens': 'always',
  'printWidth': 100,
  'proseWrap': 'always',
  'trailingComma': 'es5',
  'importOrder':
    ['<THIRD_PARTY_MODULES>', '^components/(.*)$', '^lib/(.*)$', '^assets/(.*)$', '^[./]'],
  'importOrderSeparation': true,
  'importOrderSortSpecifiers': true,
}
